name: socialui
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  get_it: ^3.1.0
  # Bloc for state management
  flutter_bloc: ^6.0.5
  # Value equality
  equatable: ^1.0.1
  auto_route: ^0.3.1  
  page_transition: ^1.1.7+6

flutter:
  uses-material-design: true

  assets:
    - assets/images/home_page.png
    - assets/images/fwd_arrow.png
    - assets/images/search.png
    - assets/images/char_1.png
    - assets/images/char_2.png
    - assets/images/char_3.png
    - assets/images/char_4.png
    - assets/images/char_5.png
    - assets/images/char_6.png
    - assets/images/new_char_1.png
    - assets/images/new_char_2.png
    - assets/images/new_char_3.png
    - assets/images/new_char_4.png
    - assets/images/new_char_5.png
    - assets/images/new_char_6.png
    - assets/images/plus.png
    - assets/images/bear.png
    - assets/images/action_menu.png
    - assets/images/search_white.png
    - assets/images/gradient_circle.png
    - assets/images/edit.png
    - assets/images/button_gradient.png
    
    

